# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\31890\Desktop\codefile\Utils\Packages\pyqt__\demo1\ui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 599)
        mainWindow.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 110, 100, 30))
        self.pushButton.setIconSize(QtCore.QSize(20, 16))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 160, 100, 30))
        self.pushButton_2.setIconSize(QtCore.QSize(20, 16))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 210, 100, 30))
        self.pushButton_3.setIconSize(QtCore.QSize(20, 16))
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(170, 260, 100, 30))
        self.checkBox_4.setIconSize(QtCore.QSize(20, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(320, 110, 150, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(320, 160, 150, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(320, 210, 150, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionopen = QtWidgets.QAction(mainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(mainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionclose = QtWidgets.QAction(mainWindow)
        self.actionclose.setObjectName("actionclose")
        self.actionquit = QtWidgets.QAction(mainWindow)
        self.actionquit.setObjectName("actionquit")
        self.actionHelp = QtWidgets.QAction(mainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionsave)
        self.menu.addAction(self.actionclose)
        self.menu_2.addAction(self.actionquit)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.toolBar.addAction(self.actionopen)
        self.toolBar.addAction(self.actionsave)
        self.toolBar.addAction(self.actionclose)
        self.toolBar.addAction(self.actionquit)
        self.toolBar.addAction(self.actionHelp)

        self.retranslateUi(mainWindow)
        self.actionclose.triggered.connect(mainWindow.close) # type: ignore
        self.pushButton_2.clicked.connect(mainWindow.click_pushButton_2) # type: ignore
        self.checkBox_4.clicked['bool'].connect(self.checkBox_4.setChecked) # type: ignore
        self.pushButton_3.clicked.connect(mainWindow.click_pushButton_3) # type: ignore
        self.actionHelp.triggered.connect(mainWindow.trigger_actHelp) # type: ignore
        self.pushButton.clicked.connect(self.lineEdit.clear) # type: ignore
        self.pushButton.clicked.connect(self.lineEdit_2.clear) # type: ignore
        self.pushButton.clicked.connect(self.lineEdit_3.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "测试"))
        self.pushButton.setText(_translate("mainWindow", "按钮1"))
        self.pushButton_2.setText(_translate("mainWindow", "按钮2"))
        self.pushButton_3.setText(_translate("mainWindow", "按钮3"))
        self.checkBox_4.setText(_translate("mainWindow", "按钮4"))
        self.menu.setTitle(_translate("mainWindow", "文件"))
        self.menu_2.setTitle(_translate("mainWindow", "退出"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.actionopen.setText(_translate("mainWindow", "打开"))
        self.actionsave.setText(_translate("mainWindow", "保存"))
        self.actionclose.setText(_translate("mainWindow", "关闭"))
        self.actionquit.setText(_translate("mainWindow", "退出"))
        self.actionHelp.setText(_translate("mainWindow", "Help"))
        self.actionHelp.setToolTip(_translate("mainWindow", "Help"))
